/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:792415:
  total = 128;
} //_CODE_:button1:792415:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:252634:
  total = 0;
} //_CODE_:button2:252634:

public void option1_clicked1(GOption source, GEvent event) { //_CODE_:option1:397724:
  println("option1 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:option1:397724:

public void option2_clicked1(GOption source, GEvent event) { //_CODE_:option2:290101:
  println("option2 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:option2:290101:

public void option3_clicked1(GOption source, GEvent event) { //_CODE_:option3:874378:
  println("option3 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:option3:874378:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  button1 = new GButton(this, 30, 34, 80, 30);
  button1.setText("Blue Team");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 130, 35, 80, 30);
  button2.setText("Red Team");
  button2.addEventHandler(this, "button2_click1");
  togGroup1 = new GToggleGroup();
  option1 = new GOption(this, 36, 121, 120, 20);
  option1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option1.setText("First Station");
  option1.setOpaque(false);
  option1.addEventHandler(this, "option1_clicked1");
  option2 = new GOption(this, 36, 141, 120, 20);
  option2.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option2.setText("Second Station");
  option2.setOpaque(false);
  option2.addEventHandler(this, "option2_clicked1");
  option3 = new GOption(this, 36, 161, 120, 22);
  option3.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option3.setText("Third Station");
  option3.setOpaque(false);
  option3.addEventHandler(this, "option3_clicked1");
  togGroup1.addControl(option1);
  togGroup1.addControl(option2);
  togGroup1.addControl(option3);
  option3.setSelected(true);
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GToggleGroup togGroup1; 
GOption option1; 
GOption option2; 
GOption option3; 

